# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alarma' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alarma
  pod 'SwiftLint'
  pod 'lottie-ios'
  pod 'Reusable'
  pod 'RealmSwift'
  pod 'SwiftCron'
#  pod 'RWMRecurrenceRule', '~> 0.0.2'

  target 'AlarmaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlarmaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
